sudo: required

language: cpp
services:
  - docker

#before_install:
#  - docker pull ubuntu:16.04
#  - docker pull ubuntu:18.04
#  - docker pull ubuntu:20.04

script:
  - docker build . -f .travis/Dockerfile.ubuntu1604
  - docker build . -f .travis/Dockerfile.ubuntu1804
  - docker build . -f .travis/Dockerfile.ubuntu2004

#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#albertlauncher"
#    on_success: never  # default: always
#    on_failure: always # default: always
